### PR TITLE
Gracefully Close Database Connector

### PR DESCRIPTION
**Pull request by sophiadt**
Wanted a mechanism to properly close the database connector and this PR is chaining the pipeline finish event from the Graph Database Writer all the way down to the database connector.

### CODE REVIEW

**Review by zprobst — CHANGES_REQUESTED** [review]
Thanks for the PR @sophiadt! 

I think this approach will work for us. A couple requests:
 - Can we  add `finish` to the ABCs for the executor and the ingest strategies? In the case of the executor I think a reasonable default is to simply `pass`? 
 - Is it possible to add a test case or two to cover the added lines?

**Comment by zprobst** [comment]
I've also approved the CI run. I suspect we may see a linter error or two crop up.

**Comment by sophiadt** [comment]
Hi @zprobst!
I've added the abstract methods and tests now 👍

**Review by zprobst — APPROVED** [review]
This looks good now! Thanks for the contribution and collaboration!

**Pull request merged**
